// <auto-generated />
using System;
using Aircnc.FrontStage.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aircnc.FrontStage.Migrations
{
    [DbContext(typeof(AircncContext))]
    [Migration("20220323134219_OrderSeed")]
    partial class OrderSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int")
                        .HasComment("身分別Enum(主管理者、小管理者)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AccountName = "MainAdmin",
                            Password = "123",
                            Permission = 1
                        },
                        new
                        {
                            AdminId = 2,
                            AccountName = "SubAdmin01",
                            Password = "1234",
                            Permission = 2
                        },
                        new
                        {
                            AdminId = 3,
                            AccountName = "SubAdmin02",
                            Password = "1234",
                            Permission = 2
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.Property<int>("BankVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("收款帳戶驗證Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasComment("後台驗者者(誰審核的)");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime")
                        .HasComment("使用者申請驗證時間");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("銀行帳號");

                    b.Property<string>("BankbookImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("帳本封面照");

                    b.Property<DateTime>("CertificationTime")
                        .HasColumnType("datetime")
                        .HasComment("後台驗證通過時間");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("驗證狀態Enum(驗證通過、未驗證");

                    b.HasKey("BankVerificationId");

                    b.HasIndex(new[] { "AdminId" }, "IX_BankVerification_AdminId");

                    b.ToTable("BankVerification");

                    b.HasData(
                        new
                        {
                            BankVerificationId = 1,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(7973),
                            BankAccount = "80222222222220",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(8204),
                            Status = 1
                        },
                        new
                        {
                            BankVerificationId = 2,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(8805),
                            BankAccount = "80222222222221",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(8809),
                            Status = 1
                        },
                        new
                        {
                            BankVerificationId = 3,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(8811),
                            BankAccount = "80222222222222",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(8812),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("CommentContent");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<double>("Stars")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Comment_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_Comment_UserId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            Stars = 4.0,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Stars = 3.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 3,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            Stars = 2.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 4,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Stars = 5.0,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 5,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            Stars = 5.0,
                            UserId = 6
                        },
                        new
                        {
                            CommentId = 6,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Stars = 4.0,
                            UserId = 7
                        },
                        new
                        {
                            CommentId = 7,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 6,
                            Stars = 4.0,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 8,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Stars = 3.0,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasComment("收信人");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasComment("發信人");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MessageId");

                    b.HasIndex(new[] { "RecipientId" }, "IX_Message_RecipientId");

                    b.HasIndex(new[] { "SenderId" }, "IX_Message_SenderId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(2782),
                            SenderId = 1,
                            Text = "HI"
                        },
                        new
                        {
                            MessageId = 2,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(3022),
                            SenderId = 1,
                            Text = "HI"
                        },
                        new
                        {
                            MessageId = 3,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(3026),
                            SenderId = 1,
                            Text = "HI"
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CkeckIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CkeckOut")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("折扣");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int")
                        .HasComment("訂購人數");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("這張訂單的原價(如果定很多晚，會是每晚單價的加總)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int")
                        .HasComment("付款方式Enum()");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int")
                        .HasComment("訂購房源數");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("付款狀態Enum(已付款未入住、已付款已入住、退款處理中、已退款)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Order_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_Order_UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Address = "台中市",
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestCount = 2,
                            OriginalPrice = 2000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            Address = "花蓮市",
                            BedCount = 2,
                            BookingDateTime = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestCount = 4,
                            OriginalPrice = 6000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 3,
                            Address = "台中市",
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestCount = 2,
                            OriginalPrice = 2000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 4,
                            Address = "台中市",
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestCount = 1,
                            OriginalPrice = 1000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 5,
                            Address = "新竹市",
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestCount = 2,
                            OriginalPrice = 1500m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            Status = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BathroomCount")
                        .HasColumnType("int");

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseType")
                        .HasColumnType("int")
                        .HasComment("房源類型enum(特色房源etc)，看ron的切板頁");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Pax")
                        .HasColumnType("int")
                        .HasComment("房客人數");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int")
                        .HasComment("房間類型enum(套房雅房等etc)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasComment("enum房源狀態(建立中/已上架/已下架)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("房東");

                    b.HasKey("RoomId");

                    b.HasIndex(new[] { "HouseType" }, "IX_Room_HouseType");

                    b.HasIndex(new[] { "RoomType" }, "IX_Room_RoomType");

                    b.HasIndex(new[] { "UserId" }, "IX_Room_UserId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "內湖區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "星雲小屋",
                            RoomType = 1,
                            Status = 2,
                            Street = "石潭路88號",
                            UnitPrice = 2310m,
                            UserId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            BathroomCount = 2,
                            BedCount = 2,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "松山區",
                            HouseType = 2,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "小葉-懶人-溫馨寬敞的樓中樓套房,青山綠樹景色,適合宅度假",
                            RoomType = 2,
                            Status = 2,
                            Street = "南京東路3段25號9樓",
                            UnitPrice = 710m,
                            UserId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            BathroomCount = 2,
                            BedCount = 1,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "南港區",
                            HouseType = 3,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "景觀雙人房A25，免費早餐、交通方便、溫馨舒適",
                            RoomType = 3,
                            Status = 2,
                            Street = "東新街116-3號",
                            UnitPrice = 500m,
                            UserId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            BathroomCount = 2,
                            BedCount = 5,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "大安區",
                            HouseType = 4,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 5,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "303魚池白宮",
                            RoomType = 3,
                            Status = 2,
                            Street = "敦化南路二段201號",
                            UnitPrice = 1110m,
                            UserId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            BathroomCount = 2,
                            BedCount = 2,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "中正區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            RoomCount = 2,
                            RoomDescription = "優質房源",
                            RoomName = "捷運站步行3分鐘 近夜市與101 Near MRT & Taipei 101",
                            RoomType = 2,
                            Status = 2,
                            Street = "林森南路17號",
                            UnitPrice = 990m,
                            UserId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "士林區",
                            HouseType = 5,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "1 min walk to YounChun MRT, center of Taipei city",
                            RoomType = 1,
                            Status = 2,
                            Street = "福德路57巷2號1樓",
                            UnitPrice = 3210m,
                            UserId = 2
                        },
                        new
                        {
                            RoomId = 7,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "新北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "永和區",
                            HouseType = 2,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "榮星花園旁靜巷溫馨小宅～適合親子同遊！",
                            RoomType = 2,
                            Status = 2,
                            Street = "中正路570號",
                            UnitPrice = 1495m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 8,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "新北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "三重區",
                            HouseType = 3,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "[K] 38 ✦ 大雙人房 含獨立衛浴 沙發",
                            RoomType = 3,
                            Status = 2,
                            Street = "大仁街44號",
                            UnitPrice = 865m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomCalendar", b =>
                {
                    b.Property<int>("RoomCalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastChangeTime")
                        .HasColumnType("datetime")
                        .HasComment("更新時間");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("月曆房東自行備註");

                    b.Property<int>("RoomCalendarStatus")
                        .HasColumnType("int")
                        .HasComment("enum被更改的狀態(被屏蔽、被訂)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("更改的單價");

                    b.HasKey("RoomCalendarId");

                    b.HasIndex(new[] { "RoomCalendarStatus" }, "IX_RoomCalendar_RoomCalendarStatusId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomCalendar_RoomId");

                    b.ToTable("RoomCalendar");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomImg", b =>
                {
                    b.Property<int>("RoomImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.HasKey("RoomImgId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomImg_RoomId");

                    b.ToTable("RoomImg");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomServiceLabel", b =>
                {
                    b.Property<int>("RoomServiceLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfLabel")
                        .HasColumnType("int")
                        .HasComment("enum(wifi,etc...)");

                    b.HasKey("RoomServiceLabelId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomServiceLabel_RoomId");

                    b.HasIndex(new[] { "TypeOfLabel" }, "IX_RoomServiceLabel_TypeOfLabeId");

                    b.ToTable("RoomServiceLabel");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.TransactionStatus", b =>
                {
                    b.Property<int>("TransactionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StatusType")
                        .HasColumnType("int")
                        .HasComment("交易狀態Enum(還在系統、已轉帳給房東、已退款給房客)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("扣除平台抽成後付給房東的金額");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("房東Id");

                    b.HasKey("TransactionStatusId");

                    b.HasIndex(new[] { "AdminId" }, "IX_TransactionStatus_AdminId");

                    b.HasIndex(new[] { "OrderId" }, "IX_TransactionStatus_OrderId");

                    b.HasIndex(new[] { "UserId" }, "IX_TransactionStatus_UserId");

                    b.ToTable("TransactionStatus");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankVerificationId")
                        .HasColumnType("int")
                        .HasComment("收款帳戶驗證Id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserVerificationId")
                        .HasColumnType("int")
                        .HasComment("身分驗證Id");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "BankVerificationId" }, "IX_User_AccountVerificationId");

                    b.HasIndex(new[] { "UserVerificationId" }, "IX_User_UserVerificationId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "台北市大安區建國南路一段96號",
                            BankVerificationId = 1,
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(598),
                            Email = "123@gmail.com",
                            EmergencyContactName = "你爸",
                            EmergencyContactPhone = "0911111111",
                            Gender = true,
                            IsDelete = false,
                            Name = "Bill",
                            Password = "123",
                            Phone = "0911123123",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            UserVerificationId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "台北市大安區建國南路一段966號",
                            BankVerificationId = 2,
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1514),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "你爸",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            Name = "c老師",
                            Password = "1234",
                            Phone = "091112315553",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            UserVerificationId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Address = "台北市大安區建國南路一段9266號",
                            BankVerificationId = 3,
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1521),
                            Email = "1232d@gmail.com",
                            Gender = false,
                            IsDelete = true,
                            Name = "曹老師",
                            Password = "1234",
                            Phone = "09111231512121",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            UserVerificationId = 3
                        },
                        new
                        {
                            UserId = 4,
                            Address = "台北市大安區建國南路一段966號33",
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1524),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "你爸",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            Name = "d老師",
                            Password = "1234",
                            Phone = "091112315553",
                            Photo = "https://picsum.photos/seed/picsum/200/300"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "台北市大安區建國南路一段966號12",
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1527),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "你爸f",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            Name = "d5老師",
                            Password = "1234",
                            Phone = "091112315553",
                            Photo = "https://picsum.photos/seed/picsum/200/300"
                        },
                        new
                        {
                            UserId = 6,
                            Address = "台北市大安區建國南路一段9566號11",
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1529),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "你爸fff",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            Name = "d老師",
                            Password = "1234",
                            Phone = "091112315553",
                            Photo = "https://picsum.photos/seed/picsum/200/300"
                        },
                        new
                        {
                            UserId = 7,
                            Address = "台北市大安區建國南路一段9266號",
                            Birthday = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 3, 23, 21, 42, 19, 159, DateTimeKind.Local).AddTicks(1531),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "你爸",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            Name = "d老師",
                            Password = "1234",
                            Phone = "091112315553",
                            Photo = "https://picsum.photos/seed/picsum/200/300"
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.Property<int>("UserVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("身分驗證Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasComment("後台驗者者(誰審核的)");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime")
                        .HasComment("使用者申請驗證時間");

                    b.Property<DateTime?>("CertificationTime")
                        .HasColumnType("datetime")
                        .HasComment("後台驗證通過時間");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasComment("驗證文件Enum(身分證、護照、駕照)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("驗證狀態IdEnum(驗證通過、未驗證");

                    b.HasKey("UserVerificationId");

                    b.HasIndex(new[] { "AdminId" }, "IX_UserVerification_AdminId");

                    b.ToTable("UserVerification");

                    b.HasData(
                        new
                        {
                            UserVerificationId = 1,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 156, DateTimeKind.Local).AddTicks(9181),
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(5602),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 2,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(6456),
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(6462),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 3,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(6464),
                            CertificationTime = new DateTime(2022, 3, 23, 21, 42, 19, 157, DateTimeKind.Local).AddTicks(6464),
                            DocumentType = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.WishList", b =>
                {
                    b.Property<int>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishListId");

                    b.HasIndex(new[] { "RoomId" }, "IX_WishList_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_WishList_UserId");

                    b.HasIndex(new[] { "WishListId" }, "IX_WishList_WishListId");

                    b.ToTable("WishList");

                    b.HasData(
                        new
                        {
                            WishListId = 1,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            UserId = 1
                        },
                        new
                        {
                            WishListId = 2,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            UserId = 2
                        },
                        new
                        {
                            WishListId = 3,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            UserId = 3
                        },
                        new
                        {
                            WishListId = 4,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            UserId = 4
                        },
                        new
                        {
                            WishListId = 5,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            UserId = 5
                        },
                        new
                        {
                            WishListId = 6,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 6,
                            UserId = 6
                        },
                        new
                        {
                            WishListId = 7,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            UserId = 6
                        },
                        new
                        {
                            WishListId = 8,
                            CreateTime = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("BankVerifications")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_BankVerification_Admin")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Comment", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("Comments")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Comment_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Comment_User")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Message", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "Recipient")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("FK_Message_User")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Message_User1")
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("Orders")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Order_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Order_User")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Room_User")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomCalendar", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomCalendars")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomCalendar_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomImg", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomImgs")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomPicture_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomServiceLabel", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomServiceLabels")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomServiceLabel_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.TransactionStatus", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_TransactionStatus_Admin")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.Order", "Order")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_TransactionStatus_Order")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_TransactionStatus_User")
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.BankVerification", "BankVerification")
                        .WithMany("Users")
                        .HasForeignKey("BankVerificationId")
                        .HasConstraintName("FK_User_BankVerification");

                    b.HasOne("Aircnc.FrontStage.Models.Entities.UserVerification", "UserVerification")
                        .WithMany("Users")
                        .HasForeignKey("UserVerificationId")
                        .HasConstraintName("FK_User_UserVerification");

                    b.Navigation("BankVerification");

                    b.Navigation("UserVerification");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("UserVerifications")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_UserVerification_Admin")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.WishList", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("WishLists")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_WishList_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_WishList_User1")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Admin", b =>
                {
                    b.Navigation("BankVerifications");

                    b.Navigation("TransactionStatuses");

                    b.Navigation("UserVerifications");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.Navigation("TransactionStatuses");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("RoomCalendars");

                    b.Navigation("RoomImgs");

                    b.Navigation("RoomServiceLabels");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MessageRecipients");

                    b.Navigation("MessageSenders");

                    b.Navigation("Orders");

                    b.Navigation("Rooms");

                    b.Navigation("TransactionStatuses");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
