// <auto-generated />
using System;
using Aircnc.FrontStage.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aircnc.FrontStage.Migrations
{
    [DbContext(typeof(AircncContext))]
    [Migration("20220509071724_addUser_typeOgLogin")]
    partial class addUser_typeOgLogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int")
                        .HasComment("身分別Enum(主管理者、小管理者)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AccountName = "MainAdmin",
                            Password = "123",
                            Permission = 1
                        },
                        new
                        {
                            AdminId = 2,
                            AccountName = "SubAdmin01",
                            Password = "1234",
                            Permission = 2
                        },
                        new
                        {
                            AdminId = 3,
                            AccountName = "SubAdmin02",
                            Password = "1234",
                            Permission = 2
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.Property<int>("BankVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("收款帳戶驗證Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasComment("後台驗者者(誰審核的)");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime")
                        .HasComment("使用者申請驗證時間");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("銀行帳號");

                    b.Property<string>("BankbookImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("帳本封面照");

                    b.Property<DateTime>("CertificationTime")
                        .HasColumnType("datetime")
                        .HasComment("後台驗證通過時間");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("驗證狀態Enum(驗證通過、未驗證");

                    b.HasKey("BankVerificationId");

                    b.HasIndex(new[] { "AdminId" }, "IX_BankVerification_AdminId");

                    b.ToTable("BankVerification");

                    b.HasData(
                        new
                        {
                            BankVerificationId = 1,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(2876),
                            BankAccount = "80222222222220",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(3220),
                            Status = 2
                        },
                        new
                        {
                            BankVerificationId = 2,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(4067),
                            BankAccount = "80222222222221",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(4071),
                            Status = 2
                        },
                        new
                        {
                            BankVerificationId = 3,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(4074),
                            BankAccount = "80222222222222",
                            BankbookImg = "https://picsum.photos/seed/picsum/200/300",
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(4075),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("CommentContent");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<double>("Stars")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Comment_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_Comment_UserId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2022, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 17,
                            Stars = 4.0,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 10,
                            Stars = 3.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 3,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2021, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 12,
                            Stars = 2.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 4,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2019, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Stars = 5.0,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 5,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 12,
                            Stars = 5.0,
                            UserId = 6
                        },
                        new
                        {
                            CommentId = 6,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Stars = 4.0,
                            UserId = 7
                        },
                        new
                        {
                            CommentId = 7,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 13,
                            Stars = 4.0,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 8,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Stars = 3.0,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 9,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2020, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Stars = 5.0,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 10,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2020, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Stars = 5.0,
                            UserId = 6
                        },
                        new
                        {
                            CommentId = 11,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 7,
                            Stars = 3.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 12,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2016, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 8,
                            Stars = 3.0,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 13,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Stars = 4.0,
                            UserId = 7
                        },
                        new
                        {
                            CommentId = 14,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            Stars = 5.0,
                            UserId = 6
                        },
                        new
                        {
                            CommentId = 15,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2017, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 15,
                            Stars = 3.0,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 16,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 14,
                            Stars = 4.0,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 17,
                            CommentContent = "環境整潔，還不錯",
                            CreateTime = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 12,
                            Stars = 4.0,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasComment("收信人");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasComment("發信人");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MessageId");

                    b.HasIndex(new[] { "RecipientId" }, "IX_Message_RecipientId");

                    b.HasIndex(new[] { "SenderId" }, "IX_Message_SenderId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(6346),
                            SenderId = 1,
                            Text = "HI"
                        },
                        new
                        {
                            MessageId = 2,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(6693),
                            SenderId = 1,
                            Text = "HI"
                        },
                        new
                        {
                            MessageId = 3,
                            RecipientId = 2,
                            SendTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(6698),
                            SenderId = 1,
                            Text = "HI"
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CkeckIn")
                        .HasColumnType("date");

                    b.Property<DateTime>("CkeckOut")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("折扣");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int")
                        .HasComment("訂購人數");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("這張訂單的原價(如果定很多晚，會是每晚單價的加總)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int")
                        .HasComment("付款方式Enum()");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int")
                        .HasComment("訂購房源數");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("付款狀態Enum(已付款未入住、已付款已入住、退款處理中、已退款)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Order_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_Order_UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            BedCount = 1,
                            BookingDateTime = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "台北市",
                            CkeckIn = new DateTime(2021, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "大安區",
                            GuestCount = 2,
                            OriginalPrice = 2000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 1,
                            RoomName = "工業風舒適雙人房",
                            Status = 1,
                            Street = "忠孝東路三段96號11樓",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            BedCount = 2,
                            BookingDateTime = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "台南市",
                            CkeckIn = new DateTime(2021, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "中西區",
                            GuestCount = 4,
                            OriginalPrice = 6000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 2,
                            RoomName = "利多文旅",
                            Status = 1,
                            Street = "西門路二段76號",
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "台北市",
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "大安區",
                            GuestCount = 2,
                            OriginalPrice = 2000m,
                            PaymentType = 2,
                            RoomCount = 1,
                            RoomId = 3,
                            RoomName = "混和宿舍:女性專用房間|光華商場 華山文創園區阜杭豆漿 捷運1分鐘 台北車站 三創",
                            Status = 2,
                            Street = "忠孝東路三段30號",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 4,
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "台中市",
                            CkeckIn = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "中區",
                            GuestCount = 1,
                            OriginalPrice = 1000m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 4,
                            RoomName = "4人車站木地板大房間|鄰近旱溪夜市",
                            Status = 3,
                            Street = "旱溪東路一段201號",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 5,
                            BedCount = 1,
                            BookingDateTime = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "新竹市",
                            CkeckIn = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "東區",
                            GuestCount = 2,
                            OriginalPrice = 1500m,
                            PaymentType = 2,
                            RoomCount = 1,
                            RoomId = 5,
                            RoomName = "背包客或騎車環島的舒適簡易單人房",
                            Status = 3,
                            Street = "經國路一段156巷",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 6,
                            BedCount = 1,
                            BookingDateTime = new DateTime(2021, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "澎湖市",
                            CkeckIn = new DateTime(2021, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CkeckOut = new DateTime(2021, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "馬公區",
                            GuestCount = 2,
                            OriginalPrice = 1500m,
                            PaymentType = 1,
                            RoomCount = 1,
                            RoomId = 6,
                            RoomName = "樂圖漫遊會館",
                            Status = 1,
                            Street = "西衛里261-8號",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.PreOrder", b =>
                {
                    b.Property<int>("PreOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CkeckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CkeckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PreOrderId");

                    b.ToTable("PreOrders");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BathroomCount")
                        .HasColumnType("int");

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseType")
                        .HasColumnType("int")
                        .HasComment("房源類型enum(特色房源etc)，看ron的切板頁");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Pax")
                        .HasColumnType("int")
                        .HasComment("房客人數");

                    b.Property<string>("RoomCheckInTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomCheckOutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int")
                        .HasComment("房間類型enum(套房雅房等etc)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasComment("enum房源狀態(建立中/已上架/已下架)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("房東");

                    b.HasKey("RoomId");

                    b.HasIndex(new[] { "HouseType" }, "IX_Room_HouseType");

                    b.HasIndex(new[] { "RoomType" }, "IX_Room_RoomType");

                    b.HasIndex(new[] { "UserId" }, "IX_Room_UserId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "內湖區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.04450m,
                            Lng = 121.52942m,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "星雲小屋",
                            RoomType = 2,
                            Status = 2,
                            Street = "石潭路88號",
                            UnitPrice = 2310m,
                            UserId = 1
                        },
                        new
                        {
                            RoomId = 3,
                            BathroomCount = 2,
                            BedCount = 1,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "南港區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.024350m,
                            Lng = 121.519432m,
                            Pax = 2,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "景觀雙人房A25，免費早餐、交通方便、溫馨舒適",
                            RoomType = 2,
                            Status = 2,
                            Street = "東新街116-3號",
                            UnitPrice = 500m,
                            UserId = 3
                        },
                        new
                        {
                            RoomId = 2,
                            BathroomCount = 2,
                            BedCount = 2,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "松山區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.043540m,
                            Lng = 121.514942m,
                            Pax = 3,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "小葉-懶人-溫馨寬敞的樓中樓套房,青山綠樹景色,適合宅度假",
                            RoomType = 2,
                            Status = 2,
                            Street = "南京東路3段25號9樓",
                            UnitPrice = 710m,
                            UserId = 2
                        },
                        new
                        {
                            RoomId = 4,
                            BathroomCount = 2,
                            BedCount = 5,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "大安區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.044150m,
                            Lng = 121.152942m,
                            Pax = 5,
                            RoomCount = 1,
                            RoomDescription = "優質房源",
                            RoomName = "303魚池白宮",
                            RoomType = 2,
                            Status = 2,
                            Street = "敦化南路二段201號",
                            UnitPrice = 1110m,
                            UserId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            BathroomCount = 2,
                            BedCount = 2,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "中正區",
                            HouseType = 1,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.104450m,
                            Lng = 121.532942m,
                            Pax = 4,
                            RoomCount = 2,
                            RoomDescription = "優質房源",
                            RoomName = "捷運站步行3分鐘 近夜市與101 Near MRT & Taipei 101",
                            RoomType = 1,
                            Status = 2,
                            Street = "林森南路17號",
                            UnitPrice = 990m,
                            UserId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "台北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "士林區",
                            HouseType = 3,
                            LastChangeTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = 25.043430m,
                            Lng = 121.352942m,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "1 min walk to YounChun MRT, center of Taipei city",
                            RoomType = 1,
                            Status = 1,
                            Street = "福德路57巷2號1樓",
                            UnitPrice = 3210m,
                            UserId = 2
                        },
                        new
                        {
                            RoomId = 7,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "新北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "永和區",
                            HouseType = 2,
                            Lat = 25.044350m,
                            Lng = 121.529432m,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "榮星花園旁靜巷溫馨小宅～適合親子同遊！",
                            RoomType = 3,
                            Status = 2,
                            Street = "中正路570號",
                            UnitPrice = 1495m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 8,
                            BathroomCount = 2,
                            BedCount = 3,
                            City = "新北市",
                            Country = "台灣",
                            CreateTime = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "三重區",
                            HouseType = 1,
                            Lat = 25.044530m,
                            Lng = 121.529342m,
                            Pax = 6,
                            RoomCount = 3,
                            RoomDescription = "優質房源",
                            RoomName = "[K] 38 ✦ 大雙人房 含獨立衛浴 沙發",
                            RoomType = 1,
                            Status = 2,
                            Street = "大仁街44號",
                            UnitPrice = 865m,
                            UserId = 5
                        },
                        new
                        {
                            RoomId = 9,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "南投縣",
                            Country = "台灣",
                            CreateTime = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "南投市",
                            HouseType = 1,
                            Lat = 25.044503m,
                            Lng = 121.523942m,
                            Pax = 4,
                            RoomCount = 2,
                            RoomDescription = "超級優質",
                            RoomName = "免費午餐，交通方便、溫馨舒適",
                            RoomType = 2,
                            Status = 1,
                            Street = "省府路130號",
                            UnitPrice = 950m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 10,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "彰化縣",
                            Country = "台灣",
                            CreateTime = new DateTime(2019, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "彰化市",
                            HouseType = 3,
                            Lat = 25.044350m,
                            Lng = 121.529342m,
                            Pax = 3,
                            RoomCount = 2,
                            RoomDescription = "一定要來",
                            RoomName = "溫馨有事，超大床",
                            RoomType = 1,
                            Status = 1,
                            Street = "中山路二段",
                            UnitPrice = 1560m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 11,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "屏東縣",
                            Country = "台灣",
                            CreateTime = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "新埤鄉",
                            HouseType = 3,
                            Lat = 25.044250m,
                            Lng = 121.522942m,
                            Pax = 2,
                            RoomCount = 2,
                            RoomDescription = "必需來住 必需來住 必需來住 必需來住",
                            RoomName = "免費午餐，鄰近夜市",
                            RoomType = 3,
                            Status = 3,
                            Street = "中正路66號",
                            UnitPrice = 1230m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 12,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "台東縣",
                            Country = "台灣",
                            CreateTime = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "台東市",
                            HouseType = 2,
                            Lat = 25.044510m,
                            Lng = 121.529242m,
                            Pax = 1,
                            RoomCount = 2,
                            RoomDescription = "鄰近花園 可以慢跑",
                            RoomName = "交通方便、溫馨舒適，超大床",
                            RoomType = 2,
                            Status = 1,
                            Street = "南京路19號",
                            UnitPrice = 2890m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 13,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "台南市",
                            Country = "台灣",
                            CreateTime = new DateTime(2015, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "麻豆區",
                            HouseType = 1,
                            Lat = 25.044530m,
                            Lng = 121.529412m,
                            Pax = 1,
                            RoomCount = 2,
                            RoomDescription = "這裡超吵 不要來",
                            RoomName = "免費午餐，語言交換，超大床",
                            RoomType = 1,
                            Status = 1,
                            Street = "忠孝路250號",
                            UnitPrice = 600m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 14,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "桃園市",
                            Country = "台灣",
                            CreateTime = new DateTime(2016, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "桃園區",
                            HouseType = 3,
                            Lat = 25.044504m,
                            Lng = 121.529442m,
                            Pax = 2,
                            RoomCount = 2,
                            RoomDescription = "我們這裡床位，有午餐",
                            RoomName = "漫步在雲端，語言交換，超大床",
                            RoomType = 1,
                            Status = 1,
                            Street = "縣府路1號",
                            UnitPrice = 500m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 15,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "台中市",
                            Country = "台灣",
                            CreateTime = new DateTime(2017, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "西屯區",
                            HouseType = 1,
                            Lat = 25.044520m,
                            Lng = 121.529422m,
                            Pax = 3,
                            RoomCount = 2,
                            RoomDescription = "我們這裡大床位，有免費歪泛",
                            RoomName = "免費午餐，溫馨寬敞的樓中樓套房，超大床",
                            RoomType = 2,
                            Status = 1,
                            Street = "台灣大道3段99號",
                            UnitPrice = 400m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 16,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "高雄市",
                            Country = "台灣",
                            CreateTime = new DateTime(2018, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "苓雅區",
                            HouseType = 2,
                            Lat = 25.044250m,
                            Lng = 121.529422m,
                            Pax = 4,
                            RoomCount = 2,
                            RoomDescription = "我們這裡大位 來騎車",
                            RoomName = "免費午餐，交通方便",
                            RoomType = 3,
                            Status = 1,
                            Street = "凱旋2路132-1號號",
                            UnitPrice = 300m,
                            UserId = 6
                        },
                        new
                        {
                            RoomId = 17,
                            BathroomCount = 1,
                            BedCount = 2,
                            City = "花蓮縣",
                            Country = "台灣",
                            CreateTime = new DateTime(2019, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "花蓮市",
                            HouseType = 2,
                            Lat = 25.044520m,
                            Lng = 121.529242m,
                            Pax = 2,
                            RoomCount = 2,
                            RoomDescription = "大車位，有回饋",
                            RoomName = "免費午餐，語言交換，超大床",
                            RoomType = 1,
                            Status = 1,
                            Street = "府前路17號",
                            UnitPrice = 750m,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomCalendar", b =>
                {
                    b.Property<int>("RoomCalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastChangeTime")
                        .HasColumnType("datetime")
                        .HasComment("更新時間");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("月曆房東自行備註");

                    b.Property<int>("RoomCalendarStatus")
                        .HasColumnType("int")
                        .HasComment("enum被更改的狀態(被屏蔽、被訂)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("更改的單價");

                    b.HasKey("RoomCalendarId");

                    b.HasIndex(new[] { "RoomCalendarStatus" }, "IX_RoomCalendar_RoomCalendarStatusId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomCalendar_RoomId");

                    b.ToTable("RoomCalendar");

                    b.HasData(
                        new
                        {
                            RoomCalendarId = 1,
                            Date = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastChangeTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "價格異動",
                            RoomCalendarStatus = 1,
                            RoomId = 1,
                            UnitPrice = 2000m
                        },
                        new
                        {
                            RoomCalendarId = 2,
                            Date = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastChangeTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "價格異動",
                            RoomCalendarStatus = 1,
                            RoomId = 2,
                            UnitPrice = 3000m
                        },
                        new
                        {
                            RoomCalendarId = 3,
                            Date = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastChangeTime = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "今天不租",
                            RoomCalendarStatus = 1,
                            RoomId = 1,
                            UnitPrice = 2000m
                        },
                        new
                        {
                            RoomCalendarId = 4,
                            Date = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastChangeTime = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "開啟租房",
                            RoomCalendarStatus = 1,
                            RoomId = 1,
                            UnitPrice = 2000m
                        },
                        new
                        {
                            RoomCalendarId = 5,
                            Date = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastChangeTime = new DateTime(2022, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "價格異動",
                            RoomCalendarStatus = 2,
                            RoomId = 1,
                            UnitPrice = 4500m
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomImg", b =>
                {
                    b.Property<int>("RoomImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.HasKey("RoomImgId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomImg_RoomId");

                    b.ToTable("RoomImg");

                    b.HasData(
                        new
                        {
                            RoomImgId = 1,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 1,
                            Sort = 1
                        },
                        new
                        {
                            RoomImgId = 2,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 1,
                            Sort = 2
                        },
                        new
                        {
                            RoomImgId = 3,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 1,
                            Sort = 5
                        },
                        new
                        {
                            RoomImgId = 4,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 1,
                            Sort = 3
                        },
                        new
                        {
                            RoomImgId = 5,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 1,
                            Sort = 4
                        },
                        new
                        {
                            RoomImgId = 6,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 2,
                            Sort = 1
                        },
                        new
                        {
                            RoomImgId = 7,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 2,
                            Sort = 2
                        },
                        new
                        {
                            RoomImgId = 8,
                            CreateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            RoomId = 2,
                            Sort = 3
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomServiceLabel", b =>
                {
                    b.Property<int>("RoomServiceLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfLabel")
                        .HasColumnType("int")
                        .HasComment("enum(wifi,etc...)");

                    b.HasKey("RoomServiceLabelId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomServiceLabel_RoomId");

                    b.HasIndex(new[] { "TypeOfLabel" }, "IX_RoomServiceLabel_TypeOfLabeId");

                    b.ToTable("RoomServiceLabel");

                    b.HasData(
                        new
                        {
                            RoomServiceLabelId = 1,
                            RoomId = 1,
                            TypeOfLabel = 1
                        },
                        new
                        {
                            RoomServiceLabelId = 2,
                            RoomId = 1,
                            TypeOfLabel = 2
                        },
                        new
                        {
                            RoomServiceLabelId = 3,
                            RoomId = 3,
                            TypeOfLabel = 6
                        },
                        new
                        {
                            RoomServiceLabelId = 4,
                            RoomId = 4,
                            TypeOfLabel = 3
                        },
                        new
                        {
                            RoomServiceLabelId = 5,
                            RoomId = 5,
                            TypeOfLabel = 2
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.TransactionStatus", b =>
                {
                    b.Property<int>("TransactionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StatusType")
                        .HasColumnType("int")
                        .HasComment("交易狀態Enum(還在系統、已轉帳給房東、已退款給房客)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,0)")
                        .HasComment("扣除平台抽成後付給房東的金額");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("房東Id");

                    b.HasKey("TransactionStatusId");

                    b.HasIndex(new[] { "AdminId" }, "IX_TransactionStatus_AdminId");

                    b.HasIndex(new[] { "OrderId" }, "IX_TransactionStatus_OrderId");

                    b.HasIndex(new[] { "UserId" }, "IX_TransactionStatus_UserId");

                    b.ToTable("TransactionStatus");

                    b.HasData(
                        new
                        {
                            TransactionStatusId = 1,
                            AdminId = 3,
                            CreateTime = new DateTime(2015, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            StatusType = 2,
                            TotalAmount = 1700m,
                            UserId = 7
                        },
                        new
                        {
                            TransactionStatusId = 2,
                            AdminId = 3,
                            CreateTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            StatusType = 2,
                            TotalAmount = 1900m,
                            UserId = 4
                        },
                        new
                        {
                            TransactionStatusId = 3,
                            AdminId = 2,
                            CreateTime = new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            StatusType = 3,
                            TotalAmount = 1400m,
                            UserId = 2
                        },
                        new
                        {
                            TransactionStatusId = 4,
                            AdminId = 1,
                            CreateTime = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 4,
                            StatusType = 1,
                            TotalAmount = 7100m,
                            UserId = 1
                        },
                        new
                        {
                            TransactionStatusId = 5,
                            AdminId = 2,
                            CreateTime = new DateTime(2022, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            StatusType = 1,
                            TotalAmount = 1100m,
                            UserId = 5
                        },
                        new
                        {
                            TransactionStatusId = 6,
                            AdminId = 2,
                            CreateTime = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            StatusType = 1,
                            TotalAmount = 5200m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankVerificationId")
                        .HasColumnType("int")
                        .HasComment("收款帳戶驗證Id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<bool>("MailIsVerify")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfLogin")
                        .HasColumnType("int");

                    b.Property<int?>("UserVerificationId")
                        .HasColumnType("int")
                        .HasComment("身分驗證Id");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "BankVerificationId" }, "IX_User_AccountVerificationId");

                    b.HasIndex(new[] { "UserVerificationId" }, "IX_User_UserVerificationId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "台北市大安區建國南路一段96號",
                            BankVerificationId = 1,
                            Birthday = new DateTime(1996, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(2879),
                            Email = "Bill123@gmail.com",
                            EmergencyContactName = "力宏",
                            EmergencyContactPhone = "0944412456",
                            Gender = true,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "Bill",
                            Password = "123",
                            Phone = "0911123123",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "台北市大安區建國南路一段966號",
                            BankVerificationId = 2,
                            Birthday = new DateTime(1997, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4378),
                            Email = "sin123d@gmail.com",
                            EmergencyContactName = "怡萱",
                            EmergencyContactPhone = "0911111111",
                            Gender = false,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "新樺",
                            Password = "1234",
                            Phone = "09122324343",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Address = "台北市大安區仁愛路一段66號",
                            BankVerificationId = 3,
                            Birthday = new DateTime(1982, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4470),
                            Email = "1232d@gmail.com",
                            Gender = false,
                            IsDelete = true,
                            MailIsVerify = true,
                            Name = "曹聖光",
                            Password = "1234",
                            Phone = "0987987987",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 3
                        },
                        new
                        {
                            UserId = 4,
                            Address = "台北市大安區忠孝東路一段420號",
                            Birthday = new DateTime(1973, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4477),
                            Email = "123dann@gmail.com",
                            EmergencyContactName = "Andy",
                            EmergencyContactPhone = "0912222222",
                            Gender = false,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "Dann",
                            Password = "1234",
                            Phone = "0912344543",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 4
                        },
                        new
                        {
                            UserId = 5,
                            Address = "台北市大安區建國南路一段966號12弄1樓",
                            Birthday = new DateTime(1998, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4482),
                            Email = "123dchen@gmail.com",
                            EmergencyContactName = "秉承",
                            EmergencyContactPhone = "0922222222",
                            Gender = false,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "陳育成",
                            Password = "1234",
                            Phone = "0913313133",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 5
                        },
                        new
                        {
                            UserId = 6,
                            Address = "台北市大安區建國南路一段9566號11樓",
                            Birthday = new DateTime(1996, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4486),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "美茜",
                            EmergencyContactPhone = "0912234234",
                            Gender = false,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "婷怡",
                            Password = "1234",
                            Phone = "0911232423",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 6
                        },
                        new
                        {
                            UserId = 7,
                            Address = "台北市大安區建國南路一段666號",
                            Birthday = new DateTime(1966, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 5, 9, 15, 17, 22, 749, DateTimeKind.Local).AddTicks(4491),
                            Email = "123d@gmail.com",
                            EmergencyContactName = "路加封",
                            EmergencyContactPhone = "0911422422",
                            Gender = false,
                            IsDelete = false,
                            MailIsVerify = true,
                            Name = "向李",
                            Password = "1234",
                            Phone = "0966666666",
                            Photo = "https://picsum.photos/seed/picsum/200/300",
                            TypeOfLogin = 0,
                            UserVerificationId = 7
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.Property<int>("UserVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("身分驗證Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasComment("後台驗者者(誰審核的)");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime")
                        .HasComment("使用者申請驗證時間");

                    b.Property<DateTime?>("CertificationTime")
                        .HasColumnType("datetime")
                        .HasComment("後台驗證通過時間");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasComment("驗證文件Enum(身分證、護照、駕照)");

                    b.Property<string>("IdPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("驗證狀態IdEnum(驗證通過、未驗證");

                    b.HasKey("UserVerificationId");

                    b.HasIndex(new[] { "AdminId" }, "IX_UserVerification_AdminId");

                    b.ToTable("UserVerification");

                    b.HasData(
                        new
                        {
                            UserVerificationId = 1,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 745, DateTimeKind.Local).AddTicks(6126),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 747, DateTimeKind.Local).AddTicks(8767),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 2,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(235),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(241),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 3,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(245),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(247),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 4,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(250),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(251),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 5,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(253),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(255),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 6,
                            AdminId = 2,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(257),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(258),
                            DocumentType = 1,
                            Status = 1
                        },
                        new
                        {
                            UserVerificationId = 7,
                            AdminId = 1,
                            ApplyTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(261),
                            CertificationTime = new DateTime(2022, 5, 9, 15, 17, 22, 748, DateTimeKind.Local).AddTicks(262),
                            DocumentType = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.WishList", b =>
                {
                    b.Property<int>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishListId");

                    b.HasIndex(new[] { "RoomId" }, "IX_WishList_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_WishList_UserId");

                    b.HasIndex(new[] { "WishListId" }, "IX_WishList_WishListId");

                    b.ToTable("WishList");

                    b.HasData(
                        new
                        {
                            WishListId = 1,
                            CreateTime = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            UserId = 1
                        },
                        new
                        {
                            WishListId = 2,
                            CreateTime = new DateTime(2015, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            UserId = 2
                        },
                        new
                        {
                            WishListId = 3,
                            CreateTime = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            UserId = 3
                        },
                        new
                        {
                            WishListId = 4,
                            CreateTime = new DateTime(2017, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            UserId = 4
                        },
                        new
                        {
                            WishListId = 5,
                            CreateTime = new DateTime(2015, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            UserId = 5
                        },
                        new
                        {
                            WishListId = 6,
                            CreateTime = new DateTime(2020, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 6,
                            UserId = 6
                        },
                        new
                        {
                            WishListId = 7,
                            CreateTime = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            UserId = 6
                        },
                        new
                        {
                            WishListId = 8,
                            CreateTime = new DateTime(2017, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("BankVerifications")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_BankVerification_Admin")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Comment", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("Comments")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Comment_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Comment_User")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Message", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "Recipient")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("FK_Message_User")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Message_User1")
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("Orders")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Order_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Order_User")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Room_User")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomCalendar", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomCalendars")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomCalendar_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomImg", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomImgs")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomPicture_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.RoomServiceLabel", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("RoomServiceLabels")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomServiceLabel_Room")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.TransactionStatus", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_TransactionStatus_Admin")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.Order", "Order")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_TransactionStatus_Order")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("TransactionStatuses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_TransactionStatus_User")
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.BankVerification", "BankVerification")
                        .WithMany("Users")
                        .HasForeignKey("BankVerificationId")
                        .HasConstraintName("FK_User_BankVerification");

                    b.HasOne("Aircnc.FrontStage.Models.Entities.UserVerification", "UserVerification")
                        .WithMany("Users")
                        .HasForeignKey("UserVerificationId")
                        .HasConstraintName("FK_User_UserVerification");

                    b.Navigation("BankVerification");

                    b.Navigation("UserVerification");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Admin", "Admin")
                        .WithMany("UserVerifications")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_UserVerification_Admin")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.WishList", b =>
                {
                    b.HasOne("Aircnc.FrontStage.Models.Entities.Room", "Room")
                        .WithMany("WishLists")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_WishList_Room")
                        .IsRequired();

                    b.HasOne("Aircnc.FrontStage.Models.Entities.User", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_WishList_User1")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Admin", b =>
                {
                    b.Navigation("BankVerifications");

                    b.Navigation("TransactionStatuses");

                    b.Navigation("UserVerifications");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.BankVerification", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Order", b =>
                {
                    b.Navigation("TransactionStatuses");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.Room", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("RoomCalendars");

                    b.Navigation("RoomImgs");

                    b.Navigation("RoomServiceLabels");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MessageRecipients");

                    b.Navigation("MessageSenders");

                    b.Navigation("Orders");

                    b.Navigation("Rooms");

                    b.Navigation("TransactionStatuses");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("Aircnc.FrontStage.Models.Entities.UserVerification", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
